CREATE TABLE usuario
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_usuario VARCHAR(255),
    apellido       VARCHAR(255),
    correo         VARCHAR(255),
    contrasena     VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);